// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type fileFileEvent struct {
	_           structs.HostLayout
	EventType   uint8
	PathMode    uint8
	Pad         [2]uint8
	Pid         uint32
	Tgid        uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	Inode       uint64
	OpenFlags   uint32
	NewMode     uint32
	StartTs     uint64
	InContainer uint8
	Pad2        [7]uint8
	Comm        [16]int8
	Filepath    [256]int8
	Filepath2   [256]int8
}

// loadFile returns the embedded CollectionSpec for file.
func loadFile() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FileBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load file: %w", err)
	}

	return spec, err
}

// loadFileObjects loads file and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*fileObjects
//	*filePrograms
//	*fileMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFileObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFile()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// fileSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileSpecs struct {
	fileProgramSpecs
	fileMapSpecs
	fileVariableSpecs
}

// fileProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileProgramSpecs struct {
	KprobeSecurityFileOpen     *ebpf.ProgramSpec `ebpf:"kprobe_security_file_open"`
	KprobeSecurityInodeRename  *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_rename"`
	KprobeSecurityInodeSetattr *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_setattr"`
	KprobeSecurityInodeUnlink  *ebpf.ProgramSpec `ebpf:"kprobe_security_inode_unlink"`
}

// fileMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileMapSpecs struct {
	ConfigMap         *ebpf.MapSpec `ebpf:"config_map"`
	FileEventScratch  *ebpf.MapSpec `ebpf:"file_event_scratch"`
	FileEvents        *ebpf.MapSpec `ebpf:"file_events"`
	FileWhitelistPids *ebpf.MapSpec `ebpf:"file_whitelist_pids"`
}

// fileVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type fileVariableSpecs struct {
}

// fileObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileObjects struct {
	filePrograms
	fileMaps
	fileVariables
}

func (o *fileObjects) Close() error {
	return _FileClose(
		&o.filePrograms,
		&o.fileMaps,
	)
}

// fileMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileMaps struct {
	ConfigMap         *ebpf.Map `ebpf:"config_map"`
	FileEventScratch  *ebpf.Map `ebpf:"file_event_scratch"`
	FileEvents        *ebpf.Map `ebpf:"file_events"`
	FileWhitelistPids *ebpf.Map `ebpf:"file_whitelist_pids"`
}

func (m *fileMaps) Close() error {
	return _FileClose(
		m.ConfigMap,
		m.FileEventScratch,
		m.FileEvents,
		m.FileWhitelistPids,
	)
}

// fileVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type fileVariables struct {
}

// filePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFileObjects or ebpf.CollectionSpec.LoadAndAssign.
type filePrograms struct {
	KprobeSecurityFileOpen     *ebpf.Program `ebpf:"kprobe_security_file_open"`
	KprobeSecurityInodeRename  *ebpf.Program `ebpf:"kprobe_security_inode_rename"`
	KprobeSecurityInodeSetattr *ebpf.Program `ebpf:"kprobe_security_inode_setattr"`
	KprobeSecurityInodeUnlink  *ebpf.Program `ebpf:"kprobe_security_inode_unlink"`
}

func (p *filePrograms) Close() error {
	return _FileClose(
		p.KprobeSecurityFileOpen,
		p.KprobeSecurityInodeRename,
		p.KprobeSecurityInodeSetattr,
		p.KprobeSecurityInodeUnlink,
	)
}

func _FileClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed file_bpfeb.o
var _FileBytes []byte
