// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type networkNetworkEvent struct {
	_           structs.HostLayout
	EventType   uint8
	IpVersion   uint8
	Protocol    uint8
	Direction   uint8
	Pid         uint32
	Tgid        uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	StartTs     uint64
	InContainer uint8
	Pad         [3]uint8
	LocalPort   uint32
	RemotePort  uint32
	LocalAddr   [16]uint8
	RemoteAddr  [16]uint8
	Comm        [16]int8
	_           [4]byte
}

// loadNetwork returns the embedded CollectionSpec for network.
func loadNetwork() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetworkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load network: %w", err)
	}

	return spec, err
}

// loadNetworkObjects loads network and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*networkObjects
//	*networkPrograms
//	*networkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadNetworkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadNetwork()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// networkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkSpecs struct {
	networkProgramSpecs
	networkMapSpecs
	networkVariableSpecs
}

// networkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkProgramSpecs struct {
	KprobeTcpConnect       *ebpf.ProgramSpec `ebpf:"kprobe_tcp_connect"`
	KprobeUdpSendmsg       *ebpf.ProgramSpec `ebpf:"kprobe_udp_sendmsg"`
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
}

// networkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkMapSpecs struct {
	ConfigMap        *ebpf.MapSpec `ebpf:"config_map"`
	NetEventScratch  *ebpf.MapSpec `ebpf:"net_event_scratch"`
	NetEvents        *ebpf.MapSpec `ebpf:"net_events"`
	NetWhitelistPids *ebpf.MapSpec `ebpf:"net_whitelist_pids"`
}

// networkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type networkVariableSpecs struct {
}

// networkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkObjects struct {
	networkPrograms
	networkMaps
	networkVariables
}

func (o *networkObjects) Close() error {
	return _NetworkClose(
		&o.networkPrograms,
		&o.networkMaps,
	)
}

// networkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkMaps struct {
	ConfigMap        *ebpf.Map `ebpf:"config_map"`
	NetEventScratch  *ebpf.Map `ebpf:"net_event_scratch"`
	NetEvents        *ebpf.Map `ebpf:"net_events"`
	NetWhitelistPids *ebpf.Map `ebpf:"net_whitelist_pids"`
}

func (m *networkMaps) Close() error {
	return _NetworkClose(
		m.ConfigMap,
		m.NetEventScratch,
		m.NetEvents,
		m.NetWhitelistPids,
	)
}

// networkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkVariables struct {
}

// networkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadNetworkObjects or ebpf.CollectionSpec.LoadAndAssign.
type networkPrograms struct {
	KprobeTcpConnect       *ebpf.Program `ebpf:"kprobe_tcp_connect"`
	KprobeUdpSendmsg       *ebpf.Program `ebpf:"kprobe_udp_sendmsg"`
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
}

func (p *networkPrograms) Close() error {
	return _NetworkClose(
		p.KprobeTcpConnect,
		p.KprobeUdpSendmsg,
		p.KretprobeInetCskAccept,
	)
}

func _NetworkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed network_bpfel.o
var _NetworkBytes []byte
