// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type processProcessEvent struct {
	_           structs.HostLayout
	EventType   uint8
	Pad         [3]uint8
	Pid         uint32
	Tgid        uint32
	Ppid        uint32
	Uid         uint32
	Gid         uint32
	ExitCode    int32
	_           [4]byte
	StartTs     uint64
	InContainer uint8
	Pad2        [7]uint8
	Comm        [16]int8
	Filename    [256]int8
	Cmdline     [512]int8
}

// loadProcess returns the embedded CollectionSpec for process.
func loadProcess() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProcessBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load process: %w", err)
	}

	return spec, err
}

// loadProcessObjects loads process and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*processObjects
//	*processPrograms
//	*processMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProcessObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProcess()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// processSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processSpecs struct {
	processProgramSpecs
	processMapSpecs
	processVariableSpecs
}

// processProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processProgramSpecs struct {
	TracepointSchedProcessExec *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exec"`
	TracepointSchedProcessExit *ebpf.ProgramSpec `ebpf:"tracepoint_sched_process_exit"`
}

// processMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processMapSpecs struct {
	ConfigMap     *ebpf.MapSpec `ebpf:"config_map"`
	EventScratch  *ebpf.MapSpec `ebpf:"event_scratch"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	WhitelistPids *ebpf.MapSpec `ebpf:"whitelist_pids"`
}

// processVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type processVariableSpecs struct {
}

// processObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processObjects struct {
	processPrograms
	processMaps
	processVariables
}

func (o *processObjects) Close() error {
	return _ProcessClose(
		&o.processPrograms,
		&o.processMaps,
	)
}

// processMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processMaps struct {
	ConfigMap     *ebpf.Map `ebpf:"config_map"`
	EventScratch  *ebpf.Map `ebpf:"event_scratch"`
	Events        *ebpf.Map `ebpf:"events"`
	WhitelistPids *ebpf.Map `ebpf:"whitelist_pids"`
}

func (m *processMaps) Close() error {
	return _ProcessClose(
		m.ConfigMap,
		m.EventScratch,
		m.Events,
		m.WhitelistPids,
	)
}

// processVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processVariables struct {
}

// processPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProcessObjects or ebpf.CollectionSpec.LoadAndAssign.
type processPrograms struct {
	TracepointSchedProcessExec *ebpf.Program `ebpf:"tracepoint_sched_process_exec"`
	TracepointSchedProcessExit *ebpf.Program `ebpf:"tracepoint_sched_process_exit"`
}

func (p *processPrograms) Close() error {
	return _ProcessClose(
		p.TracepointSchedProcessExec,
		p.TracepointSchedProcessExit,
	)
}

func _ProcessClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed process_bpfeb.o
var _ProcessBytes []byte
